Add: front-end | page from  buttongroup, Button, Dropdown
SneiderDeveloper/ui-component pull request #3
Opened 2024-04-08 23:30 UTC by josuebedoya

2024-04-10 21:20 UTC, SneiderDeveloper requested changes

2024-04-10 21:20 UTC, SneiderDeveloper commented on src/app/buttonDrop/page.tsx
El nombre debería ser buttonGroup

2024-04-10 21:20 UTC, SneiderDeveloper commented on src/app/buttonGroup/page.tsx
Por que buttonDrop y buttonGroup?

2024-04-10 21:20 UTC, SneiderDeveloper commented on src/app/layout.tsx
No debería haber cambiado las comillas simples por las dobles. Se deben utilizar siempre las simples.

2024-04-10 21:20 UTC, SneiderDeveloper commented on src/components/Button/Button.tsx
Elimina el console.log

2024-04-10 21:20 UTC, SneiderDeveloper commented on src/components/ButtonDrop/ButtonDrop.tsx
Por que ButtonDrop y ButtonGroup?. Debería quedar solo un componente llamado ButtonGroup

2024-04-10 21:20 UTC, SneiderDeveloper commented on src/components/Dropdown/Dropdown.tsx
No deberían haber cambios en Dropdown.tsx

2024-04-10 21:20 UTC, SneiderDeveloper commented on src/app/dropdown/page.tsx
No deberían haber cambios en el dropdown/page.

2024-04-10 21:20 UTC, SneiderDeveloper commented on src/components/Dropdown/Icons.tsx
No debería haber cambios en este archivo en este PR

2024-04-12 23:10 UTC, SneiderDeveloper requested changes

2024-04-12 23:10 UTC, SneiderDeveloper commented on src/app/dropdown/page.tsx
Son necesarios estos cambios en el Dropdown?

2024-04-12 23:10 UTC, SneiderDeveloper commented on src/components/ButtonGroup/ButtonGroup.tsx
El import React from "react"; en las ultimas versiones de React ya no es necesario por que se importa implícitamente. Lo puedes eliminar sin problemas.

2024-04-15 13:36 UTC, josuebedoya commented on src/app/dropdown/page.tsx
los cambios que hubieron significativos, si son necesarios que fue añadir el useState del SelectetOption

2024-04-15 23:05 UTC, merged